coverage:
  status:
    patch:
      default:
        informational: true
        wait_for_ci: false
        require_ci_to_pass: false
        
    project:
      default:
        informational: true
        wait_for_ci: false
        require_ci_to_pass: false

ignore:
  - "backend/bracket/database.py"
