coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

ignore:
  - "backend/alembic"
  - "backend/tests/integration_tests/conftest.py"
