"""create rankings table

Revision ID: 77de1c773dba
Revises: 1961954c0320
Create Date: 2024-06-29 14:13:18.278876

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str | None = "77de1c773dba"
down_revision: str | None = "1961954c0320"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rankings",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("tournament_id", sa.BigInteger(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("win_points", sa.Float(), nullable=False),
        sa.Column("draw_points", sa.Float(), nullable=False),
        sa.Column("loss_points", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tournament_id"],
            ["tournaments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rankings_id"), "rankings", ["id"], unique=False)
    op.create_index(op.f("ix_rankings_tournament_id"), "rankings", ["tournament_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rankings_tournament_id"), table_name="rankings")
    op.drop_index(op.f("ix_rankings_id"), table_name="rankings")
    op.drop_table("rankings")
    # ### end Alembic commands ###
