"""Add new Admin Account Type

Revision ID: 899415b142b1
Revises: c1ab44651e79
Create Date: 2026-01-25 15:24:12.211612

"""

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str | None = '899415b142b1'
down_revision: str | None = 'c1ab44651e79'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE account_type ADD VALUE 'ADMIN'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE account_type DROP VALUE 'ADMIN'")
    # ### end Alembic commands ###
