from typing import NewType

BreakId = NewType("BreakId", int)
ClubId = NewType("ClubId", int)
CourtId = NewType("CourtId", int)
MatchId = NewType("MatchId", int)
OfficialId = NewType("OfficialId", int)
PlayerId = NewType("PlayerId", int)
PlayerXTeamId = NewType("PlayerXTeamId", int)
RankingId = NewType("RankingId", int)
RoundId = NewType("RoundId", int)
StageId = NewType("StageId", int)
StageItemId = NewType("StageItemId", int)
StageItemInputId = NewType("StageItemInputId", int)
TeamId = NewType("TeamId", int)
TournamentId = NewType("TournamentId", int)
UserId = NewType("UserId", int)
UserXClubId = NewType("UserXClubId", int)
