name: docs test

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'docs/**'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup yarn
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock

      - name: Install npm modules
        run: yarn
        working-directory: docs

      - name: Run tests
        run: yarn test-check
        working-directory: docs

      - name: Build docs
        run: yarn build
        working-directory: docs
